/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermeniRouteImport } from './routes/termeni'
import { Route as PoliticaPlataRouteImport } from './routes/politica-plata'
import { Route as PoliticaCookiesRouteImport } from './routes/politica-cookies'
import { Route as PoliticaConfidentialitateRouteImport } from './routes/politica-confidentialitate'
import { Route as DespreRouteImport } from './routes/despre'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GhidContDiscordRouteImport } from './routes/ghid.cont-discord'

const TermeniRoute = TermeniRouteImport.update({
  id: '/termeni',
  path: '/termeni',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaPlataRoute = PoliticaPlataRouteImport.update({
  id: '/politica-plata',
  path: '/politica-plata',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaCookiesRoute = PoliticaCookiesRouteImport.update({
  id: '/politica-cookies',
  path: '/politica-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaConfidentialitateRoute =
  PoliticaConfidentialitateRouteImport.update({
    id: '/politica-confidentialitate',
    path: '/politica-confidentialitate',
    getParentRoute: () => rootRouteImport,
  } as any)
const DespreRoute = DespreRouteImport.update({
  id: '/despre',
  path: '/despre',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GhidContDiscordRoute = GhidContDiscordRouteImport.update({
  id: '/ghid/cont-discord',
  path: '/ghid/cont-discord',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/despre': typeof DespreRoute
  '/politica-confidentialitate': typeof PoliticaConfidentialitateRoute
  '/politica-cookies': typeof PoliticaCookiesRoute
  '/politica-plata': typeof PoliticaPlataRoute
  '/termeni': typeof TermeniRoute
  '/ghid/cont-discord': typeof GhidContDiscordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/despre': typeof DespreRoute
  '/politica-confidentialitate': typeof PoliticaConfidentialitateRoute
  '/politica-cookies': typeof PoliticaCookiesRoute
  '/politica-plata': typeof PoliticaPlataRoute
  '/termeni': typeof TermeniRoute
  '/ghid/cont-discord': typeof GhidContDiscordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/despre': typeof DespreRoute
  '/politica-confidentialitate': typeof PoliticaConfidentialitateRoute
  '/politica-cookies': typeof PoliticaCookiesRoute
  '/politica-plata': typeof PoliticaPlataRoute
  '/termeni': typeof TermeniRoute
  '/ghid/cont-discord': typeof GhidContDiscordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/despre'
    | '/politica-confidentialitate'
    | '/politica-cookies'
    | '/politica-plata'
    | '/termeni'
    | '/ghid/cont-discord'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/despre'
    | '/politica-confidentialitate'
    | '/politica-cookies'
    | '/politica-plata'
    | '/termeni'
    | '/ghid/cont-discord'
  id:
    | '__root__'
    | '/'
    | '/despre'
    | '/politica-confidentialitate'
    | '/politica-cookies'
    | '/politica-plata'
    | '/termeni'
    | '/ghid/cont-discord'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DespreRoute: typeof DespreRoute
  PoliticaConfidentialitateRoute: typeof PoliticaConfidentialitateRoute
  PoliticaCookiesRoute: typeof PoliticaCookiesRoute
  PoliticaPlataRoute: typeof PoliticaPlataRoute
  TermeniRoute: typeof TermeniRoute
  GhidContDiscordRoute: typeof GhidContDiscordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termeni': {
      id: '/termeni'
      path: '/termeni'
      fullPath: '/termeni'
      preLoaderRoute: typeof TermeniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-plata': {
      id: '/politica-plata'
      path: '/politica-plata'
      fullPath: '/politica-plata'
      preLoaderRoute: typeof PoliticaPlataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-cookies': {
      id: '/politica-cookies'
      path: '/politica-cookies'
      fullPath: '/politica-cookies'
      preLoaderRoute: typeof PoliticaCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-confidentialitate': {
      id: '/politica-confidentialitate'
      path: '/politica-confidentialitate'
      fullPath: '/politica-confidentialitate'
      preLoaderRoute: typeof PoliticaConfidentialitateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despre': {
      id: '/despre'
      path: '/despre'
      fullPath: '/despre'
      preLoaderRoute: typeof DespreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ghid/cont-discord': {
      id: '/ghid/cont-discord'
      path: '/ghid/cont-discord'
      fullPath: '/ghid/cont-discord'
      preLoaderRoute: typeof GhidContDiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DespreRoute: DespreRoute,
  PoliticaConfidentialitateRoute: PoliticaConfidentialitateRoute,
  PoliticaCookiesRoute: PoliticaCookiesRoute,
  PoliticaPlataRoute: PoliticaPlataRoute,
  TermeniRoute: TermeniRoute,
  GhidContDiscordRoute: GhidContDiscordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
