/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GhidContDiscordRouteImport } from './routes/ghid.cont-discord'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GhidContDiscordRoute = GhidContDiscordRouteImport.update({
  id: '/ghid/cont-discord',
  path: '/ghid/cont-discord',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ghid/cont-discord': typeof GhidContDiscordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ghid/cont-discord': typeof GhidContDiscordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ghid/cont-discord': typeof GhidContDiscordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ghid/cont-discord'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ghid/cont-discord'
  id: '__root__' | '/' | '/ghid/cont-discord'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GhidContDiscordRoute: typeof GhidContDiscordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ghid/cont-discord': {
      id: '/ghid/cont-discord'
      path: '/ghid/cont-discord'
      fullPath: '/ghid/cont-discord'
      preLoaderRoute: typeof GhidContDiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GhidContDiscordRoute: GhidContDiscordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
